<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
display(data.head(10))

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

In [5]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:**  Качество линейной регрессии не изменится

**Обоснование:** 

1.Подставим в формулу $a= Xw$ значения $w$ из формулы выше:

$$
a = X(X^T X)^{-1} X^T y
$$

Так вычисляются предсказания для не преобразованных признаков.

2.Преобразованные признаки $M$ - это матрица признаков $X$ умноженная на обратимую матрицу $P:M = XP$ 

Для преобразованных признаков формула предсказаний примет вид:

$$
a_m = M(M^T M)^{-1} M^T y = XP((XP)^T(XP))^{-1}(XP)^T y
$$

Для дальнейшего преобразования:

3.воспользуемся свойствами матриц:$(AB)^T = A^TB^T$:

$$
a_m = XP (X^TP^TXP)^{-1} X^TP^T y
$$

4.воспльзуемся свойствами обратных матриц:$(AB)^{-1} = A^{-1}B^{-1}$:

$$
a_m = XP (X^TX)^{-1} (P^T)^{-1}P^{-1} X^TP^T y
$$

$E$  - единичная матрица

5.Так как $PP^{-1} = E$, а умножение любой матрица на единичную матрицу даёт ту же матрицу $AE=A$:

$$
a_m = XE(X^TX)^{-1} E X^T y = X(X^T X)^{-1} X^T y
$$

Исходные параметры линейной регрессии:

$$
w = (X^TX)^{-1}X^Ty
$$

Преобразованные параметры линейной регрессии:

$$
w_p = ((XP)^TXP)^{-1}(XP)^Ty
$$

Мы хотим найти связь между $w$ и $w_P$. Воспользуемся свойствами матриц:

- $(AB)^T = B^T A^T$

- $(AB)^{-1} = B^{-1} A^{-1}$

Теперь применим эти свойства к формуле для преобразованных параметров:

$$
w_p = ((XP)^TXP)^{-1}(XP)^Ty
$$

- $(XP)^T XP = P^T X^T X P$

- $(P^T X^T X P)^{-1} = P^{-1} (X^T X)^{-1} (P^T)^{-1}$

Подставим полученные значения обратно в формулу:

$$
w_p = P^{-1}(X^TX)^{-1}(P^T)^{-1}(XP)^Ty
$$

Раскроем $(XP)^T$:

$$
(XP)^T = P^TX^T
$$

Теперь, подставим значение обратно в выражение для $w_p$:

$$
w_p = P^{-1}(X^TX)^{-1}(P^T)^{-1}(P^TX^T)y
$$

Заметим, что $P^{-1}(P^T)^{-1} = E$, где $E$ - единичная матрица:

$$
w_p = E(X^TX)^{-1}X^Ty
$$

Так как умножение матрицы на единичную матрицу даёт ту же матрицу ($AE = A$), то:

$$
w_p =  P^{-1}(X^TX)^{-1}X^Ty
$$

Это и есть значение весов $w$ для не преобразованных признаков, как мы видим, $ w_p = P^{-1}w$.

Теперь давайте рассмотрим предсказания $a$ и $a_m$:

$$
a = X_w
$$

$$
a_m = XP((XP)^T(XP))^{-1}(XP)^Ty
$$

Мы показали, что $w_p = w$, следовательно:

$$
a_m = Xw
$$

Таким образом, $a = a_m$, что доказывает, что качество линейной регрессии не изменится после преобразования признаков.

**Вывод:**

Таким образом уравнение для предсказаний по преобразованным признакам приобрело вид уравнения предсказаний по не преобразованным признакам

## Алгоритм преобразования

**Алгоритм**

Исходя из того, что умножение признаков на обратимую матрицу не влияет на результат работы линейной регрессии, алгоритм защиты данных пользователей будет следующий:

1. Преобразуем признаки, содержащие персональные данные клиентов в матрицу.
2. Создадим обратимую матрицу, состоящую из случайных чисел, размер которой по вертикали и горизонтали будет равен количеству признаков. Назовём данную матрицу кодирующей матрицей.
3. Произведём умножение матрицы признаков на кодирующую матрицу.

Таким образом персональные данные клиентов будут закодированны, но на результаты работы линейной регрессии это никак не скажется.

**Обоснование**

Проверим наш алгоритм на простом наборе данных. Пусть матрица признаков $X$ будет размера $2X4$

In [6]:
X = np.array([[1, 2],
             [2, 3],
             [3, 4],
             [4, 5]
            ])
X

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

Целевой признак зададим вектором $y$:

In [7]:
y = np.array([1,2,3,4])
y

array([1, 2, 3, 4])

Создадим обратимую(кодирующую) матрицу $P$  размером $2X2$

In [8]:
P = np.random.randint(1,10,(2,2))
P

array([[2, 1],
       [2, 3]])

Умножив матрицу признаков на кодирующую матрицу получим закодированную матрицу $M=XP$

In [9]:
M = X @ P
M

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

По формуле линейной регрессии $a = X (X^T X)^{-1} X^T y$ получим вектор прогнозов для не закодированных признаков:

In [10]:
a = X @ np.linalg.inv(X.T @ X) @ X.T @ y
a

array([1., 2., 3., 4.])

По этой же формуле $a_m = M (M^T M)^{-1} M^T y$ получим вектор прогнозов для закодированных признаков:

In [11]:
a_m = M @ np.linalg.inv(M.T @ M) @ M.T @ y
a

array([1., 2., 3., 4.])

**Вывод:**

Как мы видим, результаты прогноза на закодированных и не закодированных признаках получился идентичным. Осталось применить алгоритм к реальным данным и проверить результаты

## Проверка алгоритма

In [12]:
#создадим функцию кодирования
def features_coding(matrix):
    """ Функция приниммает датафрейм признаков, 
        возвращает признаки, закодированные умножением на обратимую матрицу  
    """
    np.random.seed(12345)
    if type(matrix) == pd.core.frame.DataFrame or type(matrix) == pd.core.series.Series:
        matrix = matrix.values
    range_matrix = matrix.shape[1]
    determinant = 0
    while determinant == 0:
        key_matrix = np.random.randint(1,100,(range_matrix,range_matrix))
        determinant = np.linalg.det(key_matrix)
    return matrix @ key_matrix

# Проверка работы алгоритма МО на незакодированных признаках

In [13]:
#разделим на признаки и цели
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']
#разделим на обучающую и тренировочную выборки
features_train, features_test, target_train, target_test = train_test_split(features, 
                                                                            target, 
                                                                            test_size = 0.25, 
                                                                            random_state=12345)

In [14]:
#обучим модель линейной регрессии 
lin_rg = LinearRegression()
lin_rg.fit(features_train, target_train)
predictions = lin_rg.predict(features_test)
print("R2 на незакодированных признаках:", r2_score(target_test, predictions))

R2 на незакодированных признаках: 0.43522757127027


# Проверка работы алгоритма МО на закодированных признаках

In [15]:
#кодируем признаки
features_code = features_coding(features)
#разделим на обучающую и тренировочную выборки
features_code_train, features_code_test, target_train, target_test = train_test_split(features_code, 
                                                                                      target, 
                                                                                      test_size = 0.25, 
                                                                                      random_state=12345)
features_code[0:5]

array([[2977895.,  745477., 4564510., 4017730.],
       [2282006.,  571622., 3497458., 3078103.],
       [1261218.,  316015., 1932870., 1701058.],
       [2503030.,  626259., 3837186., 3377764.],
       [1567275.,  392510., 2402042., 2114193.]])

In [16]:
#обучим модель линейной регрессии 
lin_rg_code = LinearRegression()
lin_rg_code.fit(features_code_train, target_train)
predictions_code = lin_rg_code.predict(features_code_test)
print("R2 на закодированных признаках:",r2_score(target_test, predictions_code))

R2 на закодированных признаках: 0.43522757126915324


**Вывод:**

Как видно из сравнения метрики качества моделей МО для закодированных и не закодированных данных, на качество работы модели кодирование не сказалось. На реальных данных алгоритм показал свою работоспособность

# Общий вывод:

1. Загрузили и изучили данные.
2. Ответили на вопросы и обосновали решение.
3. Создали алгоритм преобразования данных.
4. Проверели алгоритм метрикой R2 для закодированных и не закодированных данных.